#!/usr/bin/env python3
"""Standalone, single-purpose PDF text extractor, meant to be run as its
own subprocess per file rather than imported.

Why this is its own process instead of just a function in fetch.py:
extracting ~100 box score PDFs back-to-back in one long-lived Python
process produced deterministically corrupted text for a consistent subset
of files, every run, in the same order - even after ruling out download
corruption (added retries + magic-byte validation, no change), parser
bugs (checksums against known-good fixtures passed 100%), the container's
Python version (reproduced under 3.11 locally too), and the OS/platform
(the exact same file, run in isolation via the exact deployed image,
always extracts perfectly). The remaining explanation that fits every
symptom - same files failing every time, only when part of the larger
sequential loop - is pdfminer.six's internal font/CMap cache leaking
across documents that happen to reuse the same internal font name (which
these all do, since they're generated by the same VolleyStation export
template, even though each file's actual embedded glyph subset differs).
Running each extraction in a brand-new interpreter guarantees no cache
can survive between files, at the cost of one subprocess spawn per PDF -
cheap compared to the network round trip to download it in the first
place.

Reads PDF bytes from stdin, writes extracted text to stdout.
"""
import io
import sys

import pdfplumber


def main() -> None:
    data = sys.stdin.buffer.read()
    with pdfplumber.open(io.BytesIO(data)) as pdf:
        text = "\n".join(page.extract_text() or "" for page in pdf.pages)
    sys.stdout.write(text)


if __name__ == "__main__":
    main()
